- hosts: cs-checker
  tasks:

    - name: thinkerer build
      connection: local
      script: ../checkers/thinkerer/get_checker.sh

    - name: sync catalog
      synchronize: src="../checkers" dest="{{cs_dir}}"

    - name: checker owner
      file:
        path:  "{{cs_dir}}/checkers"
        owner: "{{cs_user}}"
        group: "{{cs_user}}"
        recurse: yes

    - name: install sys deps
      apt: name=python3-pip state=latest

    - name: python deps
      pip: name=requests executable=pip3
