package(default_visibility = ["//visibility:public"])

cc_library(
    name = "clientlib",
    srcs = ["thinkerer_client.cc"],
    hdrs = ["thinkerer_client.h"],
    deps = ["//proto:cpp"],
)

#cc_binary(
#    name = "client",
#    linkstatic = 1,
#    srcs = ["thinkerer_client_main.cc"],
#    deps = ["//client:clientlib", "@boost//:program_options"],
#)
