#ifndef RIBBONS_CONSTANTS_H
#define RIBBONS_CONSTANTS_H

#define NAME_SIZE 20
#define PASSWORD_SIZE 16
#define KEY_SIZE 128
#define CHANNELS_CACHE_SIZE 200
#define FOLDER "data"

#define CONNECTION_TIMEOUT 60
#define PORT 4242

#endif //RIBBONS_CONSTANTS_H
