- name: install tcpimg packages
  apt: name={{item}} state=latest
  with_items:
    - xorg
    - mplayer2
    - xterm
    - libqt5widgets5
    - libaa1-dev
    - libmikmod-dev
    - unclutter

- name: copy xorg systemd service
  copy: src=xorg.service dest=/lib/systemd/system/
  notify: enable and start xorg

- name: copy tcpimg binary
  copy: src=tcpimg dest=/root/ mode=755

- name: copy startxorg.sh binary
  copy: src=startxorg.sh dest=/root/ mode=755
