version: '2.0'
services:
  lifesim:
    build: .
    volumes:
      - .:/home/lifesim/deploy
    restart: on-failure
    mem_limit: 512m
  nginx:
    image: nginx:1.13.7-alpine
    ports:
      - "8084:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default:/etc/nginx/sites-enabled/default
      - .:/home/lifesim/deploy
    depends_on:
      - lifesim
    restart: on-failure
    mem_limit: 256m

