- name: install packages
  apt: name={{item}} state=latest
  with_items:
    - fping
    - python3-requests

- name: create users
  user: name={{item}} shell=/bin/false
  with_items:
    - networkclosed
    - antidos

- name: create cloud user
  user: name=cloud shell=/bin/bash

- name: add keys to cloud user
  authorized_key: user=cloud key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCo48pC5FtaGZ3NQ8Zh3ZQIP0UvCfgcocRtq5glV8SOZflV17tqmaBdoU4uTbUVxvD9/ON+QXmEnY+nI010Tvw2LB8uqhwMs0DQVSd3qMpCi7eRGJb7zWcCO3dEYBVwWfOYA968E2OWHmOsCjHy/+uSEedd3owUkrmTlsBkBKqVnUXk3xueiDjFd7OZhlvhF63c41Gs8RlOS1UIUlZUn0X2/uioVfP0EjsHeivPaFbdoiLI5V26mqYJgGowierCgBD9fdRr41jmHG86qNHBrZzjeVwHxRo3K6sWGFmBbDup0YTGMESOeNklF/Rscq6kdHrUmHQ0wxDKG6UmcMEM+1Dx bay@baysnotebook"

- name: create control dirs in /root
  file: path=/root/{{item}} state=directory
  with_items:
    - antidos
    - openclosenetwork
    - snat
    - trafdump
    - cloud

- name: copy sudo_cloud
  copy: src=cloud/sudo_cloud dest=/etc/sudoers.d/ mode=0640

- name: copy sudo_cloud scripts
  copy: src=cloud/{{item}} dest=/root/cloud/{{item}} mode=0755
  with_items:
    - isolate_network.sh
    - open_network.sh

- name: copy networkclosed systemd service
  copy: src=networkclosed/networkclosed.service dest=/etc/systemd/system/networkclosed.service
  notify: enable and restart networkclosed

- name: copy networkclosed service
  copy: 
    src: networkclosed/networkclosed_serv.py
    dest: /home/networkclosed/networkclosed_serv.py
    owner: networkclosed
    group: networkclosed
    mode: 0755
  notify: enable and restart networkclosed

- name: copy open-close network scripts
  copy: src=networkclosed/{{item}} dest=/root/openclosenetwork/{{item}} mode=0755
  with_items:
    - open_network.sh
    - close_network.sh
    - check_network.sh

- name: copy antidos systemd service
  copy: src=antidos/antidos.service dest=/etc/systemd/system/antidos.service
  notify: enable and restart antidos

- name: copy antidos service
  copy: 
    src: antidos/antidos_serv.py
    dest: /home/antidos/antidos_serv.py
    owner: antidos
    group: antidos
    mode: 0755
  notify: enable and restart antidos

- name: copy antidos root scripts
  copy: src=antidos/{{item}} dest=/root/antidos/{{item}} mode=0755
  with_items:
    - block_team.sh
    - unblock_team.sh
    - list_blocked_teams.sh

- name: copy snat root scripts
  copy: src=snat/{{item}} dest=/root/snat/{{item}} mode=0755
  with_items:
    - add_snat_rules.sh
    - del_snat_rules.sh
    - check_snat_rules.sh

- name: copy trafdump root scripts
  copy: src=trafdump/{{item}} dest=/root/trafdump/{{item}} mode=0755
  with_items:
    - add_trafdump_rules.sh
    - del_trafdump_rules.sh
    - check_trafdump_rules.sh
